package ventanas

import javax.swing.JButton
import javax.swing.JLabel
import javax.swing.JRadioButton
import javax.swing.JTextField

/**
 * Created by PC on 03/08/2016.
 */
public class CrearEstadoJFrame : javax.swing.JFrame() {

    /**
     * Creates new form CrearEstadoJFrame
     */
    init{
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    fun initComponents() {

        jLabel1 =  javax.swing.JLabel();
        NombreEstadoTXTField =  javax.swing.JTextField();
        EstadoInicialRadioBtn =  javax.swing.JRadioButton();
        AceptacionRadioButton =  javax.swing.JRadioButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        (jLabel1 as JLabel).setText("Nombre");

        (NombreEstadoTXTField as JTextField).addActionListener( java.awt.event.ActionListener() {
            fun actionPerformed(evt:java.awt.event.ActionEvent ) {
                NombreEstadoTXTFieldActionPerformed(evt);
            }
        });

        (EstadoInicialRadioBtn as JRadioButton).setText("Estado Inicial");
        (EstadoInicialRadioBtn as JRadioButton).addActionListener( java.awt.event.ActionListener() {
            fun actionPerformed(evt:java.awt.event.ActionEvent ) {
                EstadoInicialRadioBtnActionPerformed(evt);
            }
        });

        (AceptacionRadioButton as JRadioButton).setText("Estado De Aceptacion");
        (AceptacionRadioButton as JRadioButton).addActionListener( java.awt.event.ActionListener() {
            fun actionPerformed(evt:java.awt.event.ActionEvent ) {
                AceptacionRadioButtonActionPerformed(evt);
            }
        });


        var layout =  javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(NombreEstadoTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(EstadoInicialRadioBtn)
                                                .addGap(18, 18, 18)
                                                .addComponent(AceptacionRadioButton)))
                                .addContainerGap(45, Short.MAX_VALUE.toInt()))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE.toInt())
                                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(NombreEstadoTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(EstadoInicialRadioBtn)
                                        .addComponent(AceptacionRadioButton))
                                .addGap(18, 18, 18)
                                .addContainerGap(88, Short.MAX_VALUE.toInt()))
        );

        pack();
    }// </editor-fold>

    fun EstadoInicialRadioBtnActionPerformed( evt : java.awt.event.ActionEvent) {
        // TODO add your handling code here:
    }

    fun AceptacionRadioButtonActionPerformed(evt : java.awt.event.ActionEvent) {
        // TODO add your handling code here:
    }

    fun AceptarBtnActionPerformed(evt : java.awt.event.ActionEvent) {

    }

    fun NombreEstadoTXTFieldActionPerformed(evt : java.awt.event.ActionEvent) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    var AceptacionRadioButton: JRadioButton? = null
    var EstadoInicialRadioBtn: JRadioButton? = null
    var NombreEstadoTXTField: JTextField? = null
    var jLabel1: JLabel? = null
    // End of variables declaration
}
